// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {operations} from '../models';
import {windows} from '../models';

export function BackupDatabase(arg1:string):Promise<operations.BackupResult>;

export function BulkActivateByFilter(arg1:Record<string, any>,arg2:boolean):Promise<number>;

export function BulkActivateProducts(arg1:Array<string>,arg2:boolean):Promise<number>;

export function CancelOperation():Promise<void>;

export function ChangeFederalTributationByNCM(arg1:Array<string>,arg2:string):Promise<number>;

export function ChangeInvoiceKey(arg1:string,arg2:string,arg3:string):Promise<number>;

export function ChangeInvoiceStatus(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ChangeTributationByNCM(arg1:Array<string>,arg2:string):Promise<number>;

export function CheckConnection():Promise<boolean>;

export function CleanDatabase():Promise<void>;

export function CleanDatabaseByDate(arg1:string):Promise<number>;

export function CleanDigisatRegistry():Promise<void>;

export function CleanMovements():Promise<void>;

export function ClearLogs():Promise<void>;

export function CreateNewDatabase():Promise<void>;

export function DeleteEmitente(arg1:string):Promise<void>;

export function EnableMEI():Promise<number>;

export function FilterProducts(arg1:Record<string, any>):Promise<Record<string, any>>;

export function FindObjectIdInDatabase(arg1:string):Promise<Array<Record<string, string>>>;

export function GetDigisatProcesses():Promise<Array<windows.DigiProcess>>;

export function GetDigisatServices():Promise<Array<windows.DigiService>>;

export function GetFederalTributations():Promise<Array<Record<string, any>>>;

export function GetInvoiceByKey(arg1:string,arg2:string):Promise<operations.InvoiceDetails>;

export function GetInvoiceByNumber(arg1:string,arg2:string,arg3:string):Promise<operations.InvoiceDetails>;

export function GetInvoiceStatuses():Promise<Array<string>>;

export function GetInvoiceTypes():Promise<Array<string>>;

export function GetLogs():Promise<Array<string>>;

export function GetTotalProductCount():Promise<number>;

export function GetTributations():Promise<Array<Record<string, any>>>;

export function GetUndoableOperations():Promise<Array<Record<string, any>>>;

export function InactivateZeroProducts():Promise<number>;

export function KillDigisatProcesses():Promise<number>;

export function ListBackups(arg1:string):Promise<Array<operations.BackupResult>>;

export function ListEmitentes():Promise<Array<Record<string, any>>>;

export function RestoreDatabase(arg1:string,arg2:boolean):Promise<void>;

export function SelectBackupFile(arg1:string):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectInfoDatFile():Promise<string>;

export function StartDigisatServices():Promise<number>;

export function StopDigisatServices():Promise<number>;

export function UndoOperation(arg1:string):Promise<void>;

export function UpdateEmitenteFromFile(arg1:string):Promise<void>;

export function ZeroAllPrices():Promise<number>;

export function ZeroAllStock():Promise<number>;

export function ZeroNegativeStock():Promise<number>;
