// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustInventoryRebalance(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdjustInventoryRebalance'](arg1, arg2, arg3);
}

export function AllowSecurityExclusions() {
  return window['go']['main']['App']['AllowSecurityExclusions']();
}

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function BulkActivateByFilter(arg1, arg2) {
  return window['go']['main']['App']['BulkActivateByFilter'](arg1, arg2);
}

export function BulkActivateProducts(arg1, arg2) {
  return window['go']['main']['App']['BulkActivateProducts'](arg1, arg2);
}

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function ChangeFederalTributationByNCM(arg1, arg2) {
  return window['go']['main']['App']['ChangeFederalTributationByNCM'](arg1, arg2);
}

export function ChangeIbsCbsTributationByNCM(arg1, arg2) {
  return window['go']['main']['App']['ChangeIbsCbsTributationByNCM'](arg1, arg2);
}

export function ChangeInvoiceKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangeInvoiceKey'](arg1, arg2, arg3);
}

export function ChangeInvoiceStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChangeInvoiceStatus'](arg1, arg2, arg3, arg4);
}

export function ChangeTributationByNCM(arg1, arg2) {
  return window['go']['main']['App']['ChangeTributationByNCM'](arg1, arg2);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function CleanDatabase() {
  return window['go']['main']['App']['CleanDatabase']();
}

export function CleanDatabaseByDate(arg1) {
  return window['go']['main']['App']['CleanDatabaseByDate'](arg1);
}

export function CleanDigisatRegistry() {
  return window['go']['main']['App']['CleanDigisatRegistry']();
}

export function CleanMovements() {
  return window['go']['main']['App']['CleanMovements']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateNewDatabase() {
  return window['go']['main']['App']['CreateNewDatabase']();
}

export function DeleteEmitente(arg1) {
  return window['go']['main']['App']['DeleteEmitente'](arg1);
}

export function EnableMEI() {
  return window['go']['main']['App']['EnableMEI']();
}

export function FilterProducts(arg1) {
  return window['go']['main']['App']['FilterProducts'](arg1);
}

export function FindObjectIdInDatabase(arg1) {
  return window['go']['main']['App']['FindObjectIdInDatabase'](arg1);
}

export function GenerateInventoryReport(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['GenerateInventoryReport'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetDigisatProcesses() {
  return window['go']['main']['App']['GetDigisatProcesses']();
}

export function GetDigisatServices() {
  return window['go']['main']['App']['GetDigisatServices']();
}

export function GetFederalTributations() {
  return window['go']['main']['App']['GetFederalTributations']();
}

export function GetIbsCbsTributations() {
  return window['go']['main']['App']['GetIbsCbsTributations']();
}

export function GetInventoryValue(arg1) {
  return window['go']['main']['App']['GetInventoryValue'](arg1);
}

export function GetInvoiceByKey(arg1, arg2) {
  return window['go']['main']['App']['GetInvoiceByKey'](arg1, arg2);
}

export function GetInvoiceByNumber(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetInvoiceByNumber'](arg1, arg2, arg3);
}

export function GetInvoiceStatuses() {
  return window['go']['main']['App']['GetInvoiceStatuses']();
}

export function GetInvoiceTypes() {
  return window['go']['main']['App']['GetInvoiceTypes']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetTotalProductCount() {
  return window['go']['main']['App']['GetTotalProductCount']();
}

export function GetTributations() {
  return window['go']['main']['App']['GetTributations']();
}

export function GetUndoableOperations() {
  return window['go']['main']['App']['GetUndoableOperations']();
}

export function InactivateZeroProducts() {
  return window['go']['main']['App']['InactivateZeroProducts']();
}

export function KillDigisatProcesses() {
  return window['go']['main']['App']['KillDigisatProcesses']();
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListEmitentes() {
  return window['go']['main']['App']['ListEmitentes']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function ReleaseFirewallPorts() {
  return window['go']['main']['App']['ReleaseFirewallPorts']();
}

export function RepairMongoDBOffline() {
  return window['go']['main']['App']['RepairMongoDBOffline']();
}

export function RepairMongoDBOnline() {
  return window['go']['main']['App']['RepairMongoDBOnline']();
}

export function RestoreDatabase(arg1, arg2) {
  return window['go']['main']['App']['RestoreDatabase'](arg1, arg2);
}

export function RetryConnection() {
  return window['go']['main']['App']['RetryConnection']();
}

export function SanitizePrices(arg1) {
  return window['go']['main']['App']['SanitizePrices'](arg1);
}

export function SelectBackupFile(arg1) {
  return window['go']['main']['App']['SelectBackupFile'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectInfoDatFile() {
  return window['go']['main']['App']['SelectInfoDatFile']();
}

export function StartDigisatServices() {
  return window['go']['main']['App']['StartDigisatServices']();
}

export function StopDigisatServices() {
  return window['go']['main']['App']['StopDigisatServices']();
}

export function UndoOperation(arg1) {
  return window['go']['main']['App']['UndoOperation'](arg1);
}

export function UpdateEmitenteFromFile(arg1) {
  return window['go']['main']['App']['UpdateEmitenteFromFile'](arg1);
}

export function ZeroAllPrices() {
  return window['go']['main']['App']['ZeroAllPrices']();
}

export function ZeroAllStock() {
  return window['go']['main']['App']['ZeroAllStock']();
}

export function ZeroNegativeStock() {
  return window['go']['main']['App']['ZeroNegativeStock']();
}
